# Not working because of error: tee: /dev/fd/2: No such device or address

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - bash: |
      ./tests/ci_test.sh
    env:
      SHELL: /bin/bash
    displayName: "Tests"
