name: checks

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  # command-check:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Update repositories
  #       run: sudo apt update

  #     - name: Run tests
  #       run: |
  #         sudo apt install -y pv siege
  #         tests/ci_test.sh

  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          exclude: |
            CHANGELOG.md

  markdown-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run mdspell
        run: find . -type f \( -name "*.md" ! -name "CHANGELOG.md" \) | xargs --max-args=1 --verbose mdspell --ignore-numbers --ignore-acronyms --report --en-gb

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: ruzickap/action-my-markdown-link-checker@v1
        with:
          config_file: .mlc_config.json
          exclude: |
            CHANGELOG.md
