---
name: links

on:
  push:
    paths:
      - .github/workflows/links.yml
      - lychee.toml
  schedule:
    - cron: "0 0 * * 2"
  workflow_dispatch:

permissions: read-all

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Restore lychee cache
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a # v1.9.3
        with:
          args: ". https://ruzickap.gitbook.io/k8s-istio-demo/readme"
          fail: true
