---
name: links

on:
  push:
    paths:
      - .github/workflows/links.yml
      - lychee.toml
  schedule:
    - cron: "0 0 * * 2"
  workflow_dispatch:

permissions: read-all

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Restore lychee cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        with:
          args: ". https://ruzickap.gitbook.io/k8s-istio-demo/readme"
          fail: true
