name: terraform

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/terraform.yml
      - terraform/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/terraform.yml
      - terraform/**

permissions: read-all

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@b2ca17c0c25198c67c668c37edcbc45ca086a91e # v0.8.0
        with:
          tf_actions_version: 0.12.29
          tf_actions_subcommand: fmt
          tf_actions_working_dir: terraform/openstack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@b2ca17c0c25198c67c668c37edcbc45ca086a91e # v0.8.0
        with:
          tf_actions_version: 0.12.29
          tf_actions_subcommand: init
          tf_actions_working_dir: terraform/openstack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@b2ca17c0c25198c67c668c37edcbc45ca086a91e # v0.8.0
        with:
          tf_actions_version: 0.12.29
          tf_actions_subcommand: validate
          tf_actions_working_dir: terraform/openstack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
