name: terraform

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/terraform.yml
      - terraform/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/terraform.yml
      - terraform/**

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: latest
          tf_actions_subcommand: fmt
          tf_actions_working_dir: terraform/openstack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: latest
          tf_actions_subcommand: init
          tf_actions_working_dir: terraform/openstack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: latest
          tf_actions_subcommand: validate
          tf_actions_working_dir: terraform/openstack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
